# frontend/Dockerfile
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_API_BASE_URL
ARG VITE_API_SOCKET_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_API_SOCKET_URL=${VITE_API_SOCKET_URL}
RUN npm run build

FROM nginx:stable-alpine
# custom nginx config (we'll copy it into the image)
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

# container listens on 8082
EXPOSE 8082
CMD ["nginx", "-g", "daemon off;"]
